# Site settings
author: Joseph Romero
title: Joe's Journey to Programming
header-img: img/home-bg.png
email: joeromero47@gmail.com
copyright_name: Joseph Romero
description: > # this means to ignore newlines until "baseurl:"
  My road to learning how to program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  joeromero47

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
